spring:
  profiles: real-db
  datasource:
        url: jdbc:mariadb://street-stall-webserver.cjxaagbjsitm.ap-northeast-2.rds.amazonaws.com:3306/streetstallwebserver
        username: tlarbfuf
        password: rbfuf106203
        driver-class-name: org.mariadb.jdbc.Driver

# spring:
#   datasource:
#     url: jdbc:h2:tcp://localhost/~/streetstall
#     username: street
#     password:
#     driver-class-name: org.h2.Driver
#   jpa:
#     hibernate:
#       ddl-auto: create
#     properties:
#       hibernate:
#         # show_sql: true
#         format_sql: true
# logging.level:
#   org.hibernate.SQL: debug
# # org.hibernate.type: trace
